"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-07-03 17:54:32.789483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_currency_code')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name='uq_exchange_rate_day')
    )
    op.create_index(op.f('ix_exchange_rates_from_currency'), 'exchange_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_date'), 'exchange_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_to_currency'), 'exchange_rates', ['to_currency'], unique=False)
    op.create_table('families',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('main_responsible_member_id', sa.String(), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_owner_user_id'), 'families', ['owner_user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('relationship_type_id', sa.String(), nullable=True),
    sa.Column('relationship_serial', sa.Integer(), nullable=True),
    sa.Column('relationship_display_label', sa.String(length=80), nullable=True),
    sa.Column('invited_by_member_id', sa.String(), nullable=True),
    sa.Column('can_login_family', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invited_by_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member_user')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index(op.f('ix_family_members_role'), 'family_members', ['role'], unique=False)
    op.create_index(op.f('ix_family_members_status'), 'family_members', ['status'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('relationship_types',
    sa.Column('name_bn', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.Column('needs_serial', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_types_group_name'), 'relationship_types', ['group_name'], unique=False)
    op.create_index(op.f('ix_relationship_types_id'), 'relationship_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('accounts',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('owner_member_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('institution_name', sa.String(length=160), nullable=True),
    sa.Column('account_number_masked', sa.String(length=80), nullable=True),
    sa.Column('is_shared_family', sa.Boolean(), nullable=False),
    sa.Column('is_owner_wallet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_family_id'), 'accounts', ['family_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_owner_member_id'), 'accounts', ['owner_member_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_family_id'), 'audit_logs', ['family_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_member_id'), 'audit_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_table('categories',
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name_bn', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('category_type', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_family_id'), 'categories', ['family_id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code_hash'), 'invite_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_invite_codes_family_id'), 'invite_codes', ['family_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    op.create_index(op.f('ix_invite_codes_status'), 'invite_codes', ['status'], unique=False)
    op.create_table('member_permissions',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'permission_key', 'scope', name='uq_member_permission_scope')
    )
    op.create_index(op.f('ix_member_permissions_id'), 'member_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_member_permissions_member_id'), 'member_permissions', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_permissions_permission_key'), 'member_permissions', ['permission_key'], unique=False)
    op.create_table('notifications',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_family_id'), 'notifications', ['family_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_member_id'), 'notifications', ['member_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_severity'), 'notifications', ['severity'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('budgets',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_created_by_member_id'), 'budgets', ['created_by_member_id'], unique=False)
    op.create_index(op.f('ix_budgets_family_id'), 'budgets', ['family_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_period_type'), 'budgets', ['period_type'], unique=False)
    op.create_index(op.f('ix_budgets_status'), 'budgets', ['status'], unique=False)
    op.create_table('join_requests',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('invite_code_id', sa.String(), nullable=False),
    sa.Column('requested_role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requested_relationship_type_id', sa.String(), nullable=True),
    sa.Column('requested_relationship_label', sa.String(length=80), nullable=True),
    sa.Column('requested_relationship_serial', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_member_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_codes.id'], ),
    sa.ForeignKeyConstraint(['requested_relationship_type_id'], ['relationship_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_family_id'), 'join_requests', ['family_id'], unique=False)
    op.create_index(op.f('ix_join_requests_id'), 'join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_join_requests_status'), 'join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('owner_member_id', sa.String(), nullable=False),
    sa.Column('wallet_account_id', sa.String(), nullable=False),
    sa.Column('loan_type', sa.String(length=20), nullable=False),
    sa.Column('person_name', sa.String(length=150), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_family_id'), 'loans', ['family_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_type'), 'loans', ['loan_type'], unique=False)
    op.create_index(op.f('ix_loans_owner_member_id'), 'loans', ['owner_member_id'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index(op.f('ix_loans_wallet_account_id'), 'loans', ['wallet_account_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_account_id'), 'recurring_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_category_id'), 'recurring_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_created_by_member_id'), 'recurring_transactions', ['created_by_member_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_family_id'), 'recurring_transactions', ['family_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_frequency'), 'recurring_transactions', ['frequency'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_next_due_date'), 'recurring_transactions', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_status'), 'recurring_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_transaction_type'), 'recurring_transactions', ['transaction_type'], unique=False)
    op.create_table('savings_goals',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('owner_member_id', sa.String(), nullable=False),
    sa.Column('wallet_account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goals_family_id'), 'savings_goals', ['family_id'], unique=False)
    op.create_index(op.f('ix_savings_goals_goal_type'), 'savings_goals', ['goal_type'], unique=False)
    op.create_index(op.f('ix_savings_goals_id'), 'savings_goals', ['id'], unique=False)
    op.create_index(op.f('ix_savings_goals_owner_member_id'), 'savings_goals', ['owner_member_id'], unique=False)
    op.create_index(op.f('ix_savings_goals_status'), 'savings_goals', ['status'], unique=False)
    op.create_index(op.f('ix_savings_goals_wallet_account_id'), 'savings_goals', ['wallet_account_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=False),
    sa.Column('linked_savings_goal_id', sa.String(), nullable=True),
    sa.Column('goal_name', sa.String(length=150), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['linked_savings_goal_id'], ['savings_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_goals_created_by_member_id'), 'financial_goals', ['created_by_member_id'], unique=False)
    op.create_index(op.f('ix_financial_goals_family_id'), 'financial_goals', ['family_id'], unique=False)
    op.create_index(op.f('ix_financial_goals_goal_type'), 'financial_goals', ['goal_type'], unique=False)
    op.create_index(op.f('ix_financial_goals_id'), 'financial_goals', ['id'], unique=False)
    op.create_index(op.f('ix_financial_goals_linked_savings_goal_id'), 'financial_goals', ['linked_savings_goal_id'], unique=False)
    op.create_index(op.f('ix_financial_goals_status'), 'financial_goals', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('loan_id', sa.String(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_by_member_id'), 'transactions', ['created_by_member_id'], unique=False)
    op.create_index(op.f('ix_transactions_family_id'), 'transactions', ['family_id'], unique=False)
    op.create_index(op.f('ix_transactions_goal_id'), 'transactions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_loan_id'), 'transactions', ['loan_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('transaction_lines',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('line_type', sa.String(length=40), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_lines_account_id'), 'transaction_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_lines_id'), 'transaction_lines', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_lines_transaction_id'), 'transaction_lines', ['transaction_id'], unique=False)
    # ### end Alembic commands ###



    # Production safety patch:
    # These core foreign keys are added after all target tables exist.
    # SQLite local migration test skips ALTER ADD CONSTRAINT because SQLite
    # does not support adding named FK constraints after table creation.
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_families_main_responsible_member_id_family_members",
            "families",
            "family_members",
            ["main_responsible_member_id"],
            ["id"],
        )
        op.create_foreign_key(
            "fk_families_owner_user_id_users",
            "families",
            "users",
            ["owner_user_id"],
            ["id"],
        )
        op.create_foreign_key(
            "fk_family_members_relationship_type_id_relationship_types",
            "family_members",
            "relationship_types",
            ["relationship_type_id"],
            ["id"],
        )
        op.create_foreign_key(
            "fk_family_members_user_id_users",
            "family_members",
            "users",
            ["user_id"],
            ["id"],
        )

def downgrade() -> None:
    """Downgrade schema."""
    # Drop late-created production FK constraints first.
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint(
            "fk_family_members_user_id_users",
            "family_members",
            type_="foreignkey",
        )
        op.drop_constraint(
            "fk_family_members_relationship_type_id_relationship_types",
            "family_members",
            type_="foreignkey",
        )
        op.drop_constraint(
            "fk_families_owner_user_id_users",
            "families",
            type_="foreignkey",
        )
        op.drop_constraint(
            "fk_families_main_responsible_member_id_family_members",
            "families",
            type_="foreignkey",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_lines_transaction_id'), table_name='transaction_lines')
    op.drop_index(op.f('ix_transaction_lines_id'), table_name='transaction_lines')
    op.drop_index(op.f('ix_transaction_lines_account_id'), table_name='transaction_lines')
    op.drop_table('transaction_lines')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_loan_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_goal_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_family_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_by_member_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_financial_goals_status'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_linked_savings_goal_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_goal_type'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_family_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_created_by_member_id'), table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_savings_goals_wallet_account_id'), table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_status'), table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_owner_member_id'), table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_id'), table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_goal_type'), table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_family_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.drop_index(op.f('ix_recurring_transactions_transaction_type'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_status'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_next_due_date'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_frequency'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_family_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_created_by_member_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_category_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_account_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_loans_wallet_account_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_owner_member_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_loan_type'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_family_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_status'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_family_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_budgets_status'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_period_type'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_family_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_created_by_member_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_severity'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_member_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_family_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_member_permissions_permission_key'), table_name='member_permissions')
    op.drop_index(op.f('ix_member_permissions_member_id'), table_name='member_permissions')
    op.drop_index(op.f('ix_member_permissions_id'), table_name='member_permissions')
    op.drop_table('member_permissions')
    op.drop_index(op.f('ix_invite_codes_status'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_family_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code_hash'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_family_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_member_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_family_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_owner_member_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_family_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_relationship_types_id'), table_name='relationship_types')
    op.drop_index(op.f('ix_relationship_types_group_name'), table_name='relationship_types')
    op.drop_table('relationship_types')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_status'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_role'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_families_owner_user_id'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_exchange_rates_to_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_rate_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_from_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###